window.SEARCH_INDEX = [
  {"n": "Amul Gold Full Cream Milk", "u": "500 ml", "p": 35, "m": 36, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-01"},
  {"n": "Mother Dairy Toned Milk", "u": "500 ml", "p": 29, "m": 30, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-02"},
  {"n": "Modern White Bread", "u": "400 g", "p": 45, "m": 50, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-03"},
  {"n": "Harvest Gold Pav", "u": "200 g", "p": 30, "m": 0, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-04"},
  {"n": "Eggoz Farm Fresh Eggs", "u": "6 pcs", "p": 72, "m": 80, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-05"},
  {"n": "Keggs Farm Fresh Eggs", "u": "6 pcs", "p": 66, "m": 0, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-06"},
  {"n": "Kellogg's Corn Flakes", "u": "250 g", "p": 99, "m": 115, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-07"},
  {"n": "Nestle Koko Krunch", "u": "330 g", "p": 150, "m": 165, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-08"},
  {"n": "Amul Fresh Paneer", "u": "200 g", "p": 88, "m": 90, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-09"},
  {"n": "Mother Dairy Fresh Paneer", "u": "200 g", "p": 90, "m": 0, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-10"},
  {"n": "Amul Masti Dahi", "u": "400 g", "p": 50, "m": 55, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-11"},
  {"n": "Epigamia Greek Yogurt Natural", "u": "90 g", "p": 45, "m": 50, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-12"},
  {"n": "Amul Butter", "u": "100 g", "p": 58, "m": 62, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-13"},
  {"n": "Britannia Cheese Slices", "u": "200 g", "p": 140, "m": 150, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-14"},
  {"n": "Amul Fresh Cream", "u": "250 ml", "p": 70, "m": 75, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-15"},
  {"n": "Nestle Everyday Dairy Whitener", "u": "400 g", "p": 225, "m": 240, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-16"},
  {"n": "Amul Mithai Mate", "u": "400 g", "p": 140, "m": 0, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-17"},
  {"n": "Nestle Milkmaid", "u": "400 g", "p": 150, "m": 160, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-18"},
  {"n": "Bambino Roasted Vermicelli", "u": "400 g", "p": 52, "m": 58, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-19"},
  {"n": "MTR Vermicelli", "u": "440 g", "p": 60, "m": 65, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-20"},
  {"n": "Pintola All Natural Peanut Butter", "u": "350 g", "p": 179, "m": 249, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-21"},
  {"n": "Sundrop Peanut Butter Creamy", "u": "462 g", "p": 199, "m": 265, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-22"},
  {"n": "RiteBite Max Protein Bar", "u": "67 g", "p": 99, "m": 0, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-23"},
  {"n": "Yoga Bar Multigrain Energy Bar", "u": "38 g", "p": 40, "m": 45, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-24"},
  {"n": "Amul Sweet Lassi", "u": "200 ml", "p": 20, "m": 25, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-25"},
  {"n": "Cavin's Chocolate Milkshake", "u": "180 ml", "p": 40, "m": 45, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-26"},
  {"n": "MTR Rava Idli Mix", "u": "500 g", "p": 105, "m": 120, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-27"},
  {"n": "Gits Dhokla Mix", "u": "200 g", "p": 65, "m": 75, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-28"},
  {"n": "Dabur Honey", "u": "250 g", "p": 135, "m": 150, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-29"},
  {"n": "Dabur Chyawanprash", "u": "250 g", "p": 99, "m": 119, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-30"},
  {"n": "iD Fresh Idli & Dosa Batter", "u": "500 g", "p": 58, "m": 62, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-31"},
  {"n": "Gits Breakfast Dosa Mix", "u": "500 g", "p": 120, "m": 0, "c": "Dairy, Bread & Eggs", "h": "dairy-bread-eggs.html", "i": "images/dairy-bread-eggs/dairy-bread-eggs-32"},
  {"n": "Tomatoes", "u": "500 g", "p": 25, "m": 30, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-01"},
  {"n": "Onions", "u": "1 kg", "p": 40, "m": 45, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-02"},
  {"n": "Bananas", "u": "6 pcs", "p": 35, "m": 40, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-03"},
  {"n": "Oranges", "u": "3 pcs", "p": 60, "m": 70, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-04"},
  {"n": "Custard Apple (Sitaphal)", "u": "2 pcs", "p": 80, "m": 100, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-05"},
  {"n": "Pomegranate", "u": "2 pcs", "p": 90, "m": 110, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-06"},
  {"n": "Raw Jackfruit", "u": "500 g", "p": 55, "m": 65, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-07"},
  {"n": "Green Peas", "u": "250 g", "p": 30, "m": 35, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-08"},
  {"n": "Dragon Fruit", "u": "1 pc", "p": 250, "m": 180, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-09"},
  {"n": "Avocado", "u": "250 g", "p": 130, "m": 160, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-10"},
  {"n": "Microgreens Mix", "u": "100 g", "p": 80, "m": 95, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-11"},
  {"n": "Green Chana", "u": "200 g", "p": 30, "m": 35, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-12"},
  {"n": "Frozen Mixed Vegetables", "u": "500 g", "p": 75, "m": 90, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-13"},
  {"n": "Frozen Corn Kernels", "u": "500 g", "p": 65, "m": 80, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-14"},
  {"n": "Spinach", "u": "250 g", "p": 20, "m": 25, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-15"},
  {"n": "Coriander", "u": "100 g", "p": 15, "m": 20, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-16"},
  {"n": "Organic Carrots", "u": "500 g", "p": 55, "m": 65, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-17"},
  {"n": "Organic Tomatoes", "u": "500 g", "p": 70, "m": 85, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-18"},
  {"n": "Marigold Flowers", "u": "100 g", "p": 40, "m": 50, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-19"},
  {"n": "Curry Leaves", "u": "50 g", "p": 15, "m": 20, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-20"},
  {"n": "Hydroponic Lettuce", "u": "150 g", "p": 90, "m": 110, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-21"},
  {"n": "Hydroponic Basil", "u": "50 g", "p": 60, "m": 75, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-22"},
  {"n": "Mixed Fruit Juice", "u": "500 ml", "p": 75, "m": 90, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-23"},
  {"n": "Green Chutney", "u": "200 g", "p": 45, "m": 55, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-24"},
  {"n": "Guava", "u": "4 pcs", "p": 60, "m": 75, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-25"},
  {"n": "Papaya", "u": "1 pc", "p": 65, "m": 80, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-26"},
  {"n": "Fuji Apple", "u": "4 pcs", "p": 120, "m": 140, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-27"},
  {"n": "Nashpati (Pear)", "u": "4 pcs", "p": 90, "m": 110, "c": "Fruits & Vegetables", "h": "fruits-vegetables.html", "i": "images/fruits-vegetables/fruits-vegetables-28"},
  {"n": "Trixie Pet Waste Bags", "u": "4 rolls (60 bags)", "p": 199, "m": 249, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-01"},
  {"n": "Ferplast Atlas 10 Carrier Bag", "u": "1 pc", "p": 899, "m": 1099, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-02"},
  {"n": "Whiskas Adult Dry Cat Food (Ocean Fish)", "u": "480 g", "p": 145, "m": 160, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-03"},
  {"n": "Catit Senses 2.0 Food Tree", "u": "1 pc", "p": 1299, "m": 1599, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-04"},
  {"n": "Taiyo Pluss Discovery Goldfish Food", "u": "100 g", "p": 89, "m": 110, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-05"},
  {"n": "Boltz Small Animal Hamster Food Mix", "u": "400 g", "p": 199, "m": 249, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-06"},
  {"n": "Pedigree Adult Dry Dog Food (Chicken & Vegetables)", "u": "3 kg", "p": 649, "m": 750, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-07"},
  {"n": "Drools Focus Adult Super Premium Dog Food", "u": "3 kg", "p": 799, "m": 950, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-08"},
  {"n": "Wahl Pet-Pro Dog Clipper Kit", "u": "1 pc", "p": 2199, "m": 2799, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-09"},
  {"n": "TropiClean Oatmeal & Tea Tree Pet Shampoo", "u": "473 ml", "p": 699, "m": 849, "c": "Pet Care", "h": "pet-care.html", "i": "images/pet-care/pet-care-10"},
  {"n": "Vaseline Intensive Care Deep Moisture Body Lotion", "u": "400 ml", "p": 300, "m": 375, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-01"},
  {"n": "Nivea Cocoa Nourish Body Lotion", "u": "400 ml", "p": 340, "m": 425, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-02"},
  {"n": "Nivea Men Deep Impact Gift Pack", "u": "1 set", "p": 449, "m": 599, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-03"},
  {"n": "Fiama Shower Gel Gift Pack", "u": "1 set", "p": 399, "m": 550, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-04"},
  {"n": "Whisper Ultra Clean Sanitary Pads XL+", "u": "30 pcs", "p": 260, "m": 300, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-05"},
  {"n": "Stayfree Secure Cottony Soft XL", "u": "20 pcs", "p": 150, "m": 175, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-06"},
  {"n": "Colgate Strong Teeth Toothpaste", "u": "200 g", "p": 110, "m": 125, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-07"},
  {"n": "Sensodyne Fresh Mint Toothpaste", "u": "150 g", "p": 230, "m": 260, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-08"},
  {"n": "Dettol Liquid Handwash Refill Original", "u": "750 ml", "p": 130, "m": 160, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-09"},
  {"n": "Lifebuoy Total 10 Handwash Refill", "u": "750 ml", "p": 120, "m": 150, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-10"},
  {"n": "Garnier Micellar Cleansing Water", "u": "125 ml", "p": 165, "m": 199, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-11"},
  {"n": "Pond's Cold Cream", "u": "100 ml", "p": 130, "m": 150, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-12"},
  {"n": "Gillette Mach3 Razor", "u": "1 pc", "p": 230, "m": 270, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-13"},
  {"n": "Gillette Classic Regular Shaving Foam", "u": "418 g", "p": 300, "m": 340, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-14"},
  {"n": "Lakme Sun Expert SPF 50 Ultra Matte Gel", "u": "50 ml", "p": 375, "m": 450, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-15"},
  {"n": "Neutrogena Ultra Sheer Dry-Touch Sunscreen SPF 50+", "u": "88 ml", "p": 620, "m": 750, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-16"},
  {"n": "Head & Shoulders Cool Menthol Shampoo", "u": "650 ml", "p": 470, "m": 550, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-17"},
  {"n": "Dove Intense Repair Shampoo", "u": "650 ml", "p": 460, "m": 540, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-18"},
  {"n": "Fogg Marco Deodorant Spray", "u": "150 ml", "p": 190, "m": 225, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-19"},
  {"n": "Pond's Dreamflower Fragrant Talc", "u": "400 g", "p": 260, "m": 300, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-20"},
  {"n": "Veet Sensitive Skin Hair Removal Cream", "u": "100 g", "p": 140, "m": 170, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-21"},
  {"n": "Gillette Venus Simply Venus Razor", "u": "1 pc", "p": 200, "m": 240, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-22"},
  {"n": "Vaseline Original Petroleum Jelly", "u": "100 ml", "p": 95, "m": 110, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-23"},
  {"n": "Parachute Pure Coconut Oil", "u": "600 ml", "p": 250, "m": 285, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-24"},
  {"n": "Himalaya Purifying Neem Face Wash", "u": "150 ml", "p": 165, "m": 190, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-25"},
  {"n": "Cetaphil Gentle Skin Cleanser", "u": "125 ml", "p": 420, "m": 480, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-26"},
  {"n": "Dove Cream Beauty Bathing Bar", "u": "3 x 100 g", "p": 170, "m": 205, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-27"},
  {"n": "Lux Soft Touch Soap", "u": "4 x 100 g", "p": 190, "m": 220, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-28"},
  {"n": "Nivea Soft Light Moisturiser", "u": "300 ml", "p": 350, "m": 420, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-29"},
  {"n": "Neutrogena Hydro Boost Water Gel", "u": "50 g", "p": 680, "m": 799, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-30"},
  {"n": "Dove Deeply Nourishing Body Wash", "u": "800 ml", "p": 520, "m": 620, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-31"},
  {"n": "Fiama Magnolia & Ylang Ylang Shower Gel", "u": "250 ml", "p": 190, "m": 240, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-32"},
  {"n": "Pears Pure & Gentle Soap", "u": "3 x 125 g", "p": 230, "m": 270, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-33"},
  {"n": "Santoor Sandal & Turmeric Soap", "u": "4 x 100 g", "p": 165, "m": 195, "c": "Personal Care", "h": "personal-care.html", "i": "images/personal-care/personal-care-34"},
  {"n": "Cycle Pure Three-in-One Agarbatti", "u": "1 pack", "p": 95, "m": 110, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-01"},
  {"n": "Mangaldeep Sandal Agarbatti", "u": "1 pack", "p": 60, "m": 70, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-02"},
  {"n": "Philips Decorative LED String Light", "u": "1 pc", "p": 599, "m": 799, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-03"},
  {"n": "Wipro Garnet Decorative LED String Light", "u": "1 pc", "p": 450, "m": 599, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-04"},
  {"n": "Cycle Pure Pooja Camphor", "u": "1 pack", "p": 70, "m": 80, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-05"},
  {"n": "Ganesh Rangoli Colour Powder", "u": "1 pack", "p": 60, "m": 75, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-06"},
  {"n": "Origami Facial Tissue Box", "u": "100 pulls", "p": 60, "m": 70, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-07"},
  {"n": "Kleenex Facial Tissue Box", "u": "100 pulls", "p": 75, "m": 90, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-08"},
  {"n": "Cello Plastic Bathroom Bucket", "u": "18 L", "p": 220, "m": 275, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-09"},
  {"n": "Cello Plastic Bathroom Mug", "u": "1 pc", "p": 60, "m": 80, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-10"},
  {"n": "Yonex Mavis 350 Nylon Shuttlecock", "u": "6 pcs", "p": 550, "m": 650, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-11"},
  {"n": "Boldfit Skipping Rope", "u": "1 pc", "p": 199, "m": 399, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-12"},
  {"n": "Turtle Wax Power Out Car Wash Shampoo", "u": "500 ml", "p": 260, "m": 320, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-13"},
  {"n": "Motul C2 Chain Lube", "u": "150 ml", "p": 450, "m": 520, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-14"},
  {"n": "Party Propz Happy Birthday Banner", "u": "1 pc", "p": 120, "m": 199, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-15"},
  {"n": "Funcart Metallic Balloons", "u": "50 pcs", "p": 110, "m": 199, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-16"},
  {"n": "Taparia Screwdriver Set", "u": "1 set", "p": 250, "m": 320, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-17"},
  {"n": "Stanley Measuring Tape", "u": "5 m", "p": 300, "m": 380, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-18"},
  {"n": "Ambi Pur Car Air Freshener Vent Clip", "u": "1 pc", "p": 250, "m": 299, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-19"},
  {"n": "Godrej aer Click Car Freshener", "u": "1 pc", "p": 195, "m": 230, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-20"},
  {"n": "Nilkamal Plastic Stool", "u": "1 pc", "p": 280, "m": 350, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-21"},
  {"n": "Solimo Laundry Basket", "u": "1 pc", "p": 399, "m": 599, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-22"},
  {"n": "Amazon Pay Gift Card", "u": "₹500", "p": 500, "m": 0, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-23"},
  {"n": "Google Play Gift Code", "u": "₹500", "p": 500, "m": 0, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-24"},
  {"n": "Ugaoo Money Plant with Pot", "u": "1 pc", "p": 199, "m": 299, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-25"},
  {"n": "Ugaoo Organic Vermicompost", "u": "1 kg", "p": 99, "m": 149, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-26"},
  {"n": "Sleepwell Microfiber Pillow", "u": "1 pc", "p": 399, "m": 599, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-27"},
  {"n": "Wakefit Orthopedic Memory Foam Cervical Pillow", "u": "1 pc", "p": 899, "m": 1299, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-28"},
  {"n": "Bombay Dyeing Cushion Covers", "u": "5 pcs", "p": 349, "m": 599, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-29"},
  {"n": "Divine Casa Door Curtain", "u": "1 pc", "p": 399, "m": 699, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-30"},
  {"n": "Kuber Industries Door Mat", "u": "1 pc", "p": 199, "m": 299, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-31"},
  {"n": "Saral Home Anti-Skid Floor Mat", "u": "1 pc", "p": 249, "m": 399, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-32"},
  {"n": "Steelbird SBH-11 Full Face Helmet", "u": "1 pc", "p": 1100, "m": 1499, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-33"},
  {"n": "Bobo BM1 Jaw-Grip Bike Phone Mount", "u": "1 pc", "p": 599, "m": 999, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-34"},
  {"n": "Bombay Dyeing Cotton Double Bedsheet", "u": "1 set", "p": 899, "m": 1499, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-35"},
  {"n": "Spaces Cotton Bath Towel", "u": "1 pc", "p": 449, "m": 699, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-36"},
  {"n": "Mumbai One Card", "u": "1 pc", "p": 100, "m": 0, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-37"},
  {"n": "Delhi Metro Tourist Card", "u": "1 pc", "p": 200, "m": 0, "c": "Home & Office", "h": "home-office.html", "i": "images/home-office/home-office-38"},
  {"n": "Comfort After Wash Fabric Conditioner Morning Fresh", "u": "860 ml", "p": 205, "m": 235, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-01"},
  {"n": "Vanish Oxi Action Fabric Stain Remover Powder", "u": "400 g", "p": 140, "m": 165, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-02"},
  {"n": "Lizol Disinfectant Floor Cleaner Citrus", "u": "975 ml", "p": 200, "m": 225, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-03"},
  {"n": "Colin Glass & Household Cleaner", "u": "500 ml", "p": 95, "m": 110, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-04"},
  {"n": "Harpic Power Plus Toilet Cleaner Original", "u": "1 L", "p": 190, "m": 215, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-05"},
  {"n": "Domex Fresh Guard Disinfectant Toilet Cleaner", "u": "1 L", "p": 165, "m": 190, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-06"},
  {"n": "Odonil Room Freshener Block Lavender", "u": "75 g", "p": 55, "m": 65, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-07"},
  {"n": "Godrej Aer Spray Fresh Lush Green", "u": "240 ml", "p": 170, "m": 200, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-08"},
  {"n": "Surf Excel Easy Wash Detergent Powder", "u": "1.5 kg", "p": 210, "m": 245, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-09"},
  {"n": "Rin Advanced Detergent Bar", "u": "250 g", "p": 20, "m": 22, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-10"},
  {"n": "Vim Dishwash Liquid Gel Lemon", "u": "500 ml", "p": 105, "m": 120, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-11"},
  {"n": "Finish All in One Dishwasher Tablets", "u": "30 pcs", "p": 700, "m": 850, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-12"},
  {"n": "Scotch-Brite Microfiber Cleaning Cloth", "u": "2 pcs", "p": 130, "m": 160, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-13"},
  {"n": "Scotch-Brite Toilet Brush", "u": "1 pc", "p": 120, "m": 150, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-14"},
  {"n": "Vim Dishwash Bar Lemon", "u": "500 g", "p": 40, "m": 45, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-15"},
  {"n": "Vim Dishwash Tub Lemon", "u": "500 g", "p": 55, "m": 62, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-16"},
  {"n": "Dettol Liquid Disinfectant Original", "u": "500 ml", "p": 215, "m": 240, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-17"},
  {"n": "Dettol Disinfectant Spray Sunrise Citrus", "u": "225 ml", "p": 210, "m": 240, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-18"},
  {"n": "Scotch-Brite Scrub Pad Large", "u": "3 pcs", "p": 60, "m": 75, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-19"},
  {"n": "Scotch-Brite Kitchen Sponge Wipe", "u": "2 pcs", "p": 70, "m": 85, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-20"},
  {"n": "Kiwi Black Shoe Polish", "u": "40 ml", "p": 55, "m": 62, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-21"},
  {"n": "Kiwi Neutral Shoe Polish", "u": "40 ml", "p": 55, "m": 62, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-22"},
  {"n": "Ezee Garbage Bags Medium", "u": "30 pcs", "p": 90, "m": 110, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-23"},
  {"n": "Gala Garbage Bags Large", "u": "30 pcs", "p": 120, "m": 145, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-24"},
  {"n": "Dettol Washing Machine Cleaner Powder", "u": "3 sachets", "p": 200, "m": 240, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-25"},
  {"n": "Dr. Beckmann Service-It Washing Machine Cleaner", "u": "250 g", "p": 260, "m": 310, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-26"},
  {"n": "Surf Excel Matic Front Load Liquid Detergent", "u": "2 L", "p": 480, "m": 560, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-27"},
  {"n": "Ariel Matic Front Load Liquid Detergent", "u": "2 L", "p": 520, "m": 599, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-28"},
  {"n": "Good Knight Gold Flash Liquid Vaporizer Refill", "u": "45 ml", "p": 78, "m": 85, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-29"},
  {"n": "All Out Ultra Liquid Vaporizer Refill", "u": "45 ml", "p": 78, "m": 85, "c": "Cleaning Essentials", "h": "cleaning-essentials.html", "i": "images/cleaning-essentials/cleaning-essentials-30"},
  {"n": "Durex Extra Time Condoms", "u": "10 pcs", "p": 190, "m": 215, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-01"},
  {"n": "Manforce Dotted Condoms", "u": "10 pcs", "p": 110, "m": 125, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-02"},
  {"n": "Friends Adult Diaper Pants (M)", "u": "10 pcs", "p": 450, "m": 520, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-03"},
  {"n": "Friends Adult Diaper Pants (L)", "u": "10 pcs", "p": 480, "m": 550, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-04"},
  {"n": "Himalaya Ashvagandha Tablets", "u": "60 tabs", "p": 175, "m": 195, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-05"},
  {"n": "HealthKart HK Vitals Multivitamin", "u": "60 tabs", "p": 450, "m": 599, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-06"},
  {"n": "MuscleBlaze Biozyme Performance Whey", "u": "1 kg", "p": 3400, "m": 4499, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-07"},
  {"n": "Optimum Nutrition Gold Standard 100% Whey", "u": "2 lb", "p": 4200, "m": 5199, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-08"},
  {"n": "Dettol Antiseptic Liquid", "u": "250 ml", "p": 120, "m": 135, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-09"},
  {"n": "Savlon Antiseptic Liquid", "u": "200 ml", "p": 95, "m": 110, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-10"},
  {"n": "Dettol Instant Hand Sanitizer", "u": "200 ml", "p": 90, "m": 100, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-11"},
  {"n": "3M 9004IN N95 Mask", "u": "1 pc", "p": 75, "m": 95, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-12"},
  {"n": "Cadbury Bournvita Health Drink", "u": "750 g", "p": 340, "m": 375, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-13"},
  {"n": "Horlicks Classic Malt", "u": "500 g", "p": 260, "m": 285, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-14"},
  {"n": "Nicotex Nicotine Gum 2 mg (Mint)", "u": "9 pcs", "p": 100, "m": 110, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-15"},
  {"n": "Nicotex Nicotine Gum 4 mg (Mint)", "u": "9 pcs", "p": 110, "m": 120, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-16"},
  {"n": "Dabur Giloy Juice", "u": "500 ml", "p": 130, "m": 150, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-17"},
  {"n": "Kapiva Aloe Vera Juice", "u": "1 L", "p": 350, "m": 449, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-18"},
  {"n": "Patanjali Chyawanprash", "u": "1 kg", "p": 250, "m": 280, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-19"},
  {"n": "Zandu Chyawanprash", "u": "900 g", "p": 340, "m": 380, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-20"},
  {"n": "Omron HEM-7120 Blood Pressure Monitor", "u": "1 pc", "p": 1800, "m": 2499, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-21"},
  {"n": "Dr Morepen Gluco One BG 03 Glucometer", "u": "1 kit", "p": 950, "m": 1200, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-22"},
  {"n": "Tynor Knee Cap", "u": "1 pc", "p": 260, "m": 320, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-23"},
  {"n": "Vissco Lumbo Sacral Belt", "u": "1 pc", "p": 550, "m": 699, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-24"},
  {"n": "Dolo 650 Tablet", "u": "15 tabs", "p": 30, "m": 32, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-25"},
  {"n": "Digene Antacid Tablets (Mint)", "u": "15 tabs", "p": 25, "m": 28, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-26"},
  {"n": "Pan 40 Tablet (Pantoprazole)", "u": "15 tabs", "p": 160, "m": 175, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-27"},
  {"n": "Telma 40 Tablet (Telmisartan)", "u": "15 tabs", "p": 220, "m": 245, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-28"},
  {"n": "Fast&Up Charge Effervescent Electrolyte", "u": "20 tabs", "p": 250, "m": 300, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-29"},
  {"n": "Electral ORS Powder", "u": "21.8 g", "p": 22, "m": 24, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-30"},
  {"n": "Vicks VapoRub", "u": "25 ml", "p": 100, "m": 110, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-31"},
  {"n": "Iodex Pain Relief Balm", "u": "40 g", "p": 130, "m": 145, "c": "Pharma & Wellness", "h": "pharma-wellness.html", "i": "images/pharma-wellness/pharma-wellness-32"},
  {"n": "Pampers Active Baby Diaper Pants (M)", "u": "56 pcs", "p": 699, "m": 899, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-01"},
  {"n": "MamyPoko Pants Extra Absorb (M)", "u": "58 pcs", "p": 649, "m": 799, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-02"},
  {"n": "Johnson's Baby Head-to-Toe Wash", "u": "200 ml", "p": 150, "m": 175, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-03"},
  {"n": "Himalaya Gentle Baby Soap", "u": "75 g", "p": 55, "m": 62, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-04"},
  {"n": "Pampers Aloe Vera Baby Wipes", "u": "72 pcs", "p": 175, "m": 225, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-05"},
  {"n": "Himalaya Gentle Baby Wipes", "u": "72 pcs", "p": 165, "m": 199, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-06"},
  {"n": "Cerelac Wheat Apple Cherry (Stage 2)", "u": "300 g", "p": 250, "m": 270, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-07"},
  {"n": "Nestle NAN PRO 2 Follow-Up Formula", "u": "400 g", "p": 610, "m": 650, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-08"},
  {"n": "Johnson's Baby Lotion", "u": "200 ml", "p": 190, "m": 215, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-09"},
  {"n": "Himalaya Gentle Baby Shampoo", "u": "200 ml", "p": 150, "m": 175, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-10"},
  {"n": "Philips Avent Natural Feeding Bottle", "u": "260 ml", "p": 800, "m": 899, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-11"},
  {"n": "LuvLap Anti-Colic Baby Feeding Bottle", "u": "250 ml", "p": 250, "m": 299, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-12"},
  {"n": "Mee Mee Baby Nasal Aspirator", "u": "1 pc", "p": 120, "m": 149, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-13"},
  {"n": "LuvLap Baby Finger Toothbrush", "u": "1 pc", "p": 99, "m": 125, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-14"},
  {"n": "Pigeon Manual Breast Pump", "u": "1 pc", "p": 1150, "m": 1399, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-15"},
  {"n": "LuvLap Disposable Nursing Pads", "u": "24 pcs", "p": 199, "m": 249, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-16"},
  {"n": "Funskool Giggles Rattle Set", "u": "1 set", "p": 280, "m": 350, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-17"},
  {"n": "Fisher-Price Newborn Gift Set", "u": "1 set", "p": 899, "m": 1099, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-18"},
  {"n": "Mee Mee Baby Laundry Liquid Detergent", "u": "1.2 L", "p": 299, "m": 350, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-19"},
  {"n": "Johnson's Baby Powder", "u": "200 g", "p": 135, "m": 155, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-20"},
  {"n": "Mamaearth Anti Stretch Marks Cream", "u": "100 g", "p": 349, "m": 399, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-21"},
  {"n": "Mee Mee Maternity Pads", "u": "10 pcs", "p": 180, "m": 220, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-22"},
  {"n": "Dr Trust Digital Thermometer", "u": "1 pc", "p": 199, "m": 299, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-23"},
  {"n": "LuvLap Baby Safety Corner Guards", "u": "8 pcs", "p": 249, "m": 299, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-24"},
  {"n": "Mee Mee Baby Socks (Pack of 3)", "u": "3 pairs", "p": 150, "m": 199, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-25"},
  {"n": "Babyhug Cotton Bibs", "u": "3 pcs", "p": 199, "m": 249, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-26"},
  {"n": "LuvLap Sunshine Compact Baby Stroller", "u": "1 pc", "p": 3999, "m": 5499, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-27"},
  {"n": "R for Rabbit Cuddle Baby Bouncer", "u": "1 pc", "p": 2999, "m": 3999, "c": "Baby Care", "h": "baby-care.html", "i": "images/baby-care/baby-care-28"},
  {"n": "Saffola Gold Refined Edible Oil", "u": "1 L", "p": 175, "m": 200, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-01"},
  {"n": "Patanjali Cow's Ghee", "u": "1 L", "p": 650, "m": 700, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-02"},
  {"n": "Nature Fresh Sampoorna Atta", "u": "5 kg", "p": 260, "m": 290, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-03"},
  {"n": "Rajdhani Maida", "u": "500 g", "p": 30, "m": 34, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-04"},
  {"n": "Happilo Premium Walnut Kernels", "u": "200 g", "p": 230, "m": 300, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-05"},
  {"n": "Farmley Premium Roasted Pistachios", "u": "200 g", "p": 340, "m": 420, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-06"},
  {"n": "Tata Sampann Unpolished Urad Dal Split", "u": "500 g", "p": 90, "m": 105, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-07"},
  {"n": "24 Mantra Organic Foxtail Millet", "u": "500 g", "p": 95, "m": 110, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-08"},
  {"n": "Hellmann's Real Mayonnaise", "u": "400 g", "p": 190, "m": 220, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-09"},
  {"n": "Barilla Pesto alla Genovese", "u": "190 g", "p": 350, "m": 399, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-10"},
  {"n": "Catch Garam Masala", "u": "100 g", "p": 85, "m": 95, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-11"},
  {"n": "Borges Balsamic Vinegar of Modena", "u": "250 ml", "p": 330, "m": 380, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-12"},
  {"n": "24 Mantra Organic Sugar", "u": "1 kg", "p": 80, "m": 95, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-13"},
  {"n": "Organic Tattva Honey", "u": "500 g", "p": 280, "m": 340, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-14"},
  {"n": "Cadbury Dairy Milk Silk", "u": "150 g", "p": 175, "m": 190, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-15"},
  {"n": "Ferrero Rocher Chocolate", "u": "16 pcs", "p": 640, "m": 700, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-16"},
  {"n": "Daawat Biryani Basmati Rice", "u": "1 kg", "p": 165, "m": 195, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-17"},
  {"n": "Fortune Sona Masoori Rice", "u": "5 kg", "p": 380, "m": 430, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-18"},
  {"n": "Britannia Good Day Cashew Cookies", "u": "200 g", "p": 40, "m": 45, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-19"},
  {"n": "Sunfeast Dark Fantasy Choco Fills", "u": "300 g", "p": 125, "m": 140, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-20"},
  {"n": "Tata Tea Gold", "u": "500 g", "p": 300, "m": 335, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-21"},
  {"n": "Nescafe Classic Instant Coffee", "u": "100 g", "p": 330, "m": 380, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-22"},
  {"n": "Kellogg's Corn Flakes Original", "u": "875 g", "p": 330, "m": 380, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-23"},
  {"n": "Quaker Oats", "u": "1 kg", "p": 190, "m": 215, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-24"},
  {"n": "Tropicana Orange Delight Juice", "u": "1 L", "p": 110, "m": 125, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-25"},
  {"n": "Real Fruit Power Mixed Fruit Juice", "u": "1 L", "p": 115, "m": 130, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-26"},
  {"n": "Lay's India's Magic Masala Chips", "u": "52 g", "p": 20, "m": 20, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-27"},
  {"n": "Haldiram's Aloo Bhujia", "u": "400 g", "p": 110, "m": 125, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-28"},
  {"n": "Weikfield Baking Powder", "u": "100 g", "p": 40, "m": 45, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-29"},
  {"n": "Weikfield Cocoa Powder", "u": "50 g", "p": 60, "m": 70, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-30"},
  {"n": "Maggi 2-Minute Masala Noodles", "u": "560 g", "p": 110, "m": 120, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-31"},
  {"n": "Haldiram's Ready to Eat Dal Makhani", "u": "300 g", "p": 105, "m": 120, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-32"},
  {"n": "Blue Tribe Foods Plant Based Chicken Nuggets", "u": "200 g", "p": 220, "m": 260, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-33"},
  {"n": "GoodDot Plant Based Mutton Keema", "u": "200 g", "p": 190, "m": 220, "c": "Organic & Healthy Living", "h": "organic-healthy-living.html", "i": "images/organic-healthy-living/organic-healthy-living-34"},
  {"n": "Licious Chicken Curry Cut - Small Pieces", "u": "500 g", "p": 190, "m": 215, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-01"},
  {"n": "Licious Chicken Mince (Keema)", "u": "500 g", "p": 240, "m": 275, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-02"},
  {"n": "Eggoz Protein Rich White Eggs", "u": "6 pcs", "p": 70, "m": 78, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-03"},
  {"n": "Keggs Farm Fresh Brown Eggs", "u": "6 pcs", "p": 75, "m": 85, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-04"},
  {"n": "Venky's Chicken Nuggets", "u": "250 g", "p": 165, "m": 190, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-05"},
  {"n": "Godrej Yummiez Chicken Popcorn", "u": "250 g", "p": 170, "m": 195, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-06"},
  {"n": "Licious Chicken Breast - Boneless", "u": "450 g", "p": 265, "m": 300, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-07"},
  {"n": "FreshToHome Chicken Drumsticks", "u": "500 g", "p": 190, "m": 220, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-08"},
  {"n": "Licious Goat Curry Cut - Bone-in", "u": "500 g", "p": 650, "m": 720, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-09"},
  {"n": "FreshToHome Goat Meat Curry Cut", "u": "500 g", "p": 640, "m": 700, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-10"},
  {"n": "Licious Rohu Fish Curry Cut", "u": "500 g", "p": 260, "m": 300, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-11"},
  {"n": "Licious Tiger Prawns - Cleaned & Deveined", "u": "250 g", "p": 330, "m": 380, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-12"},
  {"n": "Prasuma Chicken Cocktail Sausages", "u": "250 g", "p": 165, "m": 190, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-13"},
  {"n": "Godrej Yummiez Chicken Salami", "u": "200 g", "p": 190, "m": 220, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-14"},
  {"n": "Licious Turkey Breast", "u": "500 g", "p": 550, "m": 620, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-15"},
  {"n": "FreshToHome Quail (Cleaned)", "u": "500 g", "p": 420, "m": 480, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-16"},
  {"n": "GoodDot Soya Chunks Plant Based Chicken Style Nuggets", "u": "250 g", "p": 185, "m": 215, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-17"},
  {"n": "Blue Tribe Foods Plant Based Chicken Seekh Kebab", "u": "200 g", "p": 225, "m": 260, "c": "Chicken, Meat & Fish", "h": "chicken-meat-fish.html", "i": "images/chicken-meat-fish/chicken-meat-fish-18"},
  {"n": "Kissan Fresh Tomato Ketchup", "u": "950 g", "p": 140, "m": 155, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-01"},
  {"n": "Maggi Hot & Sweet Tomato Chilli Sauce", "u": "500 g", "p": 110, "m": 125, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-02"},
  {"n": "Ching's Secret Schezwan Chutney", "u": "250 g", "p": 85, "m": 100, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-03"},
  {"n": "Ching's Secret Dark Soy Sauce", "u": "200 ml", "p": 55, "m": 65, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-04"},
  {"n": "Veeba Eggless Mayonnaise", "u": "250 g", "p": 75, "m": 90, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-05"},
  {"n": "Funfoods Veg Mayonnaise", "u": "250 g", "p": 80, "m": 95, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-06"},
  {"n": "Pintola All Natural Peanut Butter Creamy", "u": "350 g", "p": 175, "m": 225, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-07"},
  {"n": "Sundrop Peanut Butter Creamy", "u": "462 g", "p": 190, "m": 230, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-08"},
  {"n": "Kissan Mixed Fruit Jam", "u": "500 g", "p": 150, "m": 175, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-09"},
  {"n": "Nutella Hazelnut Spread with Cocoa", "u": "350 g", "p": 385, "m": 420, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-10"},
  {"n": "Dabur Honey", "u": "500 g", "p": 215, "m": 260, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-11"},
  {"n": "Dabur Chyawanprash", "u": "1 kg", "p": 385, "m": 425, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-12"},
  {"n": "Hershey's Chocolate Syrup", "u": "623 g", "p": 235, "m": 270, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-13"},
  {"n": "Hamdard Rooh Afza", "u": "750 ml", "p": 210, "m": 235, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-14"},
  {"n": "Mother's Recipe Mango Pickle", "u": "400 g", "p": 125, "m": 140, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-15"},
  {"n": "Mother's Recipe Mixed Pickle", "u": "400 g", "p": 125, "m": 140, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-16"},
  {"n": "Veeba Thousand Island Dressing", "u": "300 g", "p": 130, "m": 155, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-17"},
  {"n": "Veeba Cheese & Jalapeno Dip", "u": "250 g", "p": 125, "m": 150, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-18"},
  {"n": "Ching's Secret Green Chilli Sauce", "u": "190 g", "p": 50, "m": 60, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-19"},
  {"n": "Tops Red Chilli Sauce", "u": "200 g", "p": 40, "m": 50, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-20"},
  {"n": "Funfoods Pizza & Pasta Sauce", "u": "325 g", "p": 110, "m": 130, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-21"},
  {"n": "Del Monte White Vinegar", "u": "385 ml", "p": 55, "m": 65, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-22"},
  {"n": "Lotus Biscoff Cookie Butter Spread", "u": "400 g", "p": 360, "m": 420, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-23"},
  {"n": "Skippy Creamy Peanut Butter", "u": "340 g", "p": 350, "m": 399, "c": "Sauces & Spreads", "h": "sauces-spreads.html", "i": "images/sauces-spreads/sauces-spreads-24"},
  {"n": "Fortune Sunlite Refined Sunflower Oil", "u": "1 L", "p": 135, "m": 155, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-01"},
  {"n": "Fortune Premium Kachi Ghani Pure Mustard Oil", "u": "1 L", "p": 165, "m": 185, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-02"},
  {"n": "Happilo Premium California Almonds", "u": "200 g", "p": 190, "m": 250, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-03"},
  {"n": "Nutraj Premium Whole Cashews", "u": "250 g", "p": 260, "m": 320, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-04"},
  {"n": "Amul Pure Ghee", "u": "1 L", "p": 640, "m": 675, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-05"},
  {"n": "Dalda Vanaspati", "u": "1 L", "p": 145, "m": 160, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-06"},
  {"n": "Tata Sampann Cumin Seeds (Jeera)", "u": "100 g", "p": 55, "m": 65, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-07"},
  {"n": "Catch Black Pepper Whole", "u": "50 g", "p": 60, "m": 70, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-08"},
  {"n": "Everest Turmeric Powder (Haldi)", "u": "200 g", "p": 55, "m": 62, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-09"},
  {"n": "MDH Deggi Mirch Red Chilli Powder", "u": "100 g", "p": 75, "m": 85, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-10"},
  {"n": "Lion Dates Seedless", "u": "500 g", "p": 150, "m": 180, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-11"},
  {"n": "Happilo Premium Chia Seeds", "u": "200 g", "p": 130, "m": 180, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-12"},
  {"n": "Tata Salt Iodised", "u": "1 kg", "p": 28, "m": 30, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-13"},
  {"n": "Madhur Pure & Hygienic Sugar", "u": "1 kg", "p": 55, "m": 60, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-14"},
  {"n": "Lijjat Urad Papad", "u": "200 g", "p": 65, "m": 70, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-15"},
  {"n": "Lijjat Punjabi Masala Papad", "u": "200 g", "p": 70, "m": 75, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-16"},
  {"n": "Happilo Premium Assorted Dry Fruits Gift Box", "u": "500 g", "p": 749, "m": 999, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-17"},
  {"n": "Nutraj Assorted Dry Fruits Gift Pack", "u": "400 g", "p": 599, "m": 799, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-18"},
  {"n": "Kitchens of India Paneer Butter Masala Paste", "u": "80 g", "p": 70, "m": 80, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-19"},
  {"n": "Smith & Jones Ginger Garlic Paste", "u": "200 g", "p": 55, "m": 65, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-20"},
  {"n": "Everest Kasuri Methi", "u": "25 g", "p": 40, "m": 45, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-21"},
  {"n": "Keya Dried Oregano", "u": "20 g", "p": 55, "m": 65, "c": "Masala, Oil & More", "h": "masala-oil-more.html", "i": "images/masala-oil-more/masala-oil-more-22"},
  {"n": "Aashirvaad Shudh Chakki Whole Wheat Atta", "u": "5 kg", "p": 250, "m": 280, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-01"},
  {"n": "Pillsbury Chakki Fresh Atta", "u": "5 kg", "p": 245, "m": 265, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-02"},
  {"n": "India Gate Basmati Rice Classic", "u": "1 kg", "p": 135, "m": 165, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-03"},
  {"n": "Daawat Rozana Super Basmati Rice", "u": "5 kg", "p": 420, "m": 500, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-04"},
  {"n": "Tata Sampann Unpolished Toor Dal", "u": "1 kg", "p": 185, "m": 210, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-05"},
  {"n": "Tata Sampann Unpolished Chana Dal", "u": "1 kg", "p": 120, "m": 140, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-06"},
  {"n": "Tata Sampann Besan", "u": "500 g", "p": 65, "m": 75, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-07"},
  {"n": "Rajdhani Sooji (Suji)", "u": "500 g", "p": 34, "m": 38, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-08"},
  {"n": "Tata Sampann Poha Thick", "u": "500 g", "p": 48, "m": 55, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-09"},
  {"n": "Patanjali Dalia", "u": "500 g", "p": 40, "m": 45, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-10"},
  {"n": "Tata Sampann Rajma Chitra", "u": "500 g", "p": 90, "m": 105, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-11"},
  {"n": "Tata Sampann Kabuli Chana", "u": "500 g", "p": 85, "m": 100, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-12"},
  {"n": "Tata Sampann Unpolished Moong Dal", "u": "500 g", "p": 80, "m": 95, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-13"},
  {"n": "Tata Sampann Unpolished Masoor Dal", "u": "500 g", "p": 70, "m": 80, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-14"},
  {"n": "Fortune Chakki Fresh Atta", "u": "5 kg", "p": 240, "m": 265, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-15"},
  {"n": "Aashirvaad Select Sharbati Atta", "u": "5 kg", "p": 330, "m": 365, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-16"},
  {"n": "Aashirvaad Multigrain Atta", "u": "5 kg", "p": 330, "m": 375, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-17"},
  {"n": "Organic Tattva Ragi Flour", "u": "500 g", "p": 75, "m": 90, "c": "Atta, Rice & Dal", "h": "atta-rice-dal.html", "i": "images/atta-rice-dal/atta-rice-dal-18"},
  {"n": "Tata Tea Gold", "u": "250 g", "p": 125, "m": 0, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-01"},
  {"n": "Brooke Bond Red Label", "u": "250 g", "p": 140, "m": 0, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-02"},
  {"n": "Nescafe Classic Instant Coffee", "u": "90 g", "p": 369, "m": 410, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-03"},
  {"n": "BRU Instant Coffee", "u": "100 g", "p": 279, "m": 310, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-04"},
  {"n": "Horlicks Nutrition Drink", "u": "500 g", "p": 229, "m": 0, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-05"},
  {"n": "Complan Nutrition Drink", "u": "500 g", "p": 241.53, "m": 249, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-06"},
  {"n": "Lipton Honey Lemon Green Tea", "u": "100 g", "p": 170, "m": 0, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-07"},
  {"n": "Organic India Tulsi Green Tea Classic", "u": "43.5 g", "p": 228, "m": 240, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-08"},
  {"n": "Bournvita Chocolate Nutrition Drink", "u": "500 g", "p": 202.73, "m": 209, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-09"},
  {"n": "Bournvita 5 Star Magic Nutrition Drink", "u": "500 g", "p": 242.5, "m": 250, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-10"},
  {"n": "Red Bull Energy Drink", "u": "250 ml", "p": 125, "m": 0, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-11"},
  {"n": "Monster Energy Drink", "u": "350 ml", "p": 113, "m": 125, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-12"},
  {"n": "Amul Rose Lassi", "u": "1 L", "p": 90, "m": 0, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-13"},
  {"n": "Cavins Chocolate Milkshake", "u": "1 L", "p": 120, "m": 150, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-14"},
  {"n": "Sleepy Owl Classic Cold Coffee", "u": "230 ml", "p": 108.13, "m": 125, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-15"},
  {"n": "Nescafe Iced Latte Cold Coffee", "u": "170 ml", "p": 50, "m": 0, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-16"},
  {"n": "Sofit Soya Naturally Sugar Free Drink", "u": "180 ml", "p": 38.8, "m": 40, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-17"},
  {"n": "Twinings Camomile Tea", "u": "25 g (25 bags)", "p": 375.25, "m": 395, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-18"},
  {"n": "Twinings English Breakfast Tea", "u": "200 g", "p": 1092, "m": 1150, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-19"},
  {"n": "Twinings English Classics Breakfast Tea", "u": "25 pcs", "p": 327.75, "m": 345, "c": "Tea, Coffee & Milk Drinks", "h": "tea-coffee-milk-drinks.html", "i": "images/tea-coffee-milk-drinks/tea-coffee-milk-drinks-20"},
  {"n": "Open Secret Celebration Chocolate Biscuits Gift Pack (Zero Maida)", "u": "150 g", "p": 278, "m": 350, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-01"},
  {"n": "The Baker's Dozen Danish Style Butter Cookies Gift Pack", "u": "150 g", "p": 201, "m": 225, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-02"},
  {"n": "Harvest Gold 100% Atta Whole Wheat Bread", "u": "450 g", "p": 62, "m": 65, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-03"},
  {"n": "Bonn Extra Soft Pav Bread", "u": "250 g", "p": 36, "m": 40, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-04"},
  {"n": "Hide & Seek Choco Chip Cookies", "u": "100 g", "p": 29, "m": 30, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-05"},
  {"n": "Britannia Good Day Butter Cookies", "u": "248 g", "p": 38, "m": 40, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-06"},
  {"n": "Oreo Vanilla Flavour Sandwich Cream Biscuits", "u": "125.25 g", "p": 38, "m": 40, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-07"},
  {"n": "Britannia Original Bourbon Creme Biscuit", "u": "150 g", "p": 26, "m": 0, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-08"},
  {"n": "Parle-G Original Gluco Biscuit", "u": "800 g", "p": 84, "m": 90, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-09"},
  {"n": "Britannia Marie Gold Marie Biscuits", "u": "208 g", "p": 38, "m": 40, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-10"},
  {"n": "Britannia NutriChoice Digestive High-Fibre Biscuit", "u": "125 g", "p": 25, "m": 0, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-11"},
  {"n": "Sunfeast Farmlite Oats & Almonds Cookies", "u": "150 g", "p": 68, "m": 75, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-12"},
  {"n": "Britannia Toastea Premium Bake Rusk", "u": "250 g", "p": 42, "m": 50, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-13"},
  {"n": "Parle Real Elaichi Premium Rusk", "u": "291.2 g", "p": 54, "m": 60, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-14"},
  {"n": "Britannia Gobbles Fruity Fun Slice Cake", "u": "60 g", "p": 25, "m": 0, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-15"},
  {"n": "Cadbury Rich & Fudgy Brownie", "u": "114 g", "p": 85, "m": 100, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-16"},
  {"n": "Fab Vintage French Vanilla Essence", "u": "100 ml", "p": 210, "m": 225, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-17"},
  {"n": "Weikfield Baking Powder", "u": "100 g", "p": 45, "m": 0, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-18"},
  {"n": "Sunfeast Wowzers Cheese Crackers Biscuit", "u": "128 g", "p": 49, "m": 56, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-19"},
  {"n": "Britannia 5050 Cheeze Dipped Biscuit", "u": "150 g", "p": 45, "m": 50, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-20"},
  {"n": "Lotus Biscoff Original Caramelized Cookies", "u": "225 g", "p": 105, "m": 110, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-21"},
  {"n": "The Baker's Dozen Dark Chocolate Cookies", "u": "100 g", "p": 119, "m": 0, "c": "Bakery & Biscuits", "h": "bakery-biscuits.html", "i": "images/bakery-biscuits/bakery-biscuits-22"},
  {"n": "Kaju Katli by Amul", "u": "200 g", "p": 238, "m": 250, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-01"},
  {"n": "Soan Papdi by Bikano", "u": "200 g", "p": 51, "m": 55, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-02"},
  {"n": "Ferrero Rocher Chocolate Gift Pack (16 pieces)", "u": "200 g", "p": 511, "m": 539, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-03"},
  {"n": "Cadbury Celebrations Assorted Diwali Chocolate Gift Pack", "u": "51 g", "p": 44, "m": 50, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-04"},
  {"n": "Amul Vanilla Magic Ice Cream Tub", "u": "1 ltr", "p": 195, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-05"},
  {"n": "Kwality Wall's Cornetto Double Chocolate Frozen Dessert Cone", "u": "105 ml", "p": 40, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-06"},
  {"n": "Cadbury Dairy Milk Chocolate Bar", "u": "26 g", "p": 25, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-07"},
  {"n": "Amul Chocominis Chocolate Gift Pack", "u": "250 g", "p": 130, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-08"},
  {"n": "Nestle KitKat Chocolate Bar", "u": "13.2 g", "p": 20, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-09"},
  {"n": "Cadbury Dairy Milk Silk Chocolate Bar", "u": "60 g", "p": 90, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-10"},
  {"n": "Yoga Bar Chocolate Chunk Nut Multigrain Energy Bar", "u": "35 g", "p": 33, "m": 45, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-11"},
  {"n": "RiteBite Max Protein Daily Choco Almond Bar", "u": "50 g", "p": 70, "m": 71, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-12"},
  {"n": "Orbit Mixed Fruit Flavour Chewing Gum Sugar Free", "u": "19.8 g", "p": 30, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-13"},
  {"n": "Center Fresh Sugar Free Mint Candies", "u": "100 g", "p": 45, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-14"},
  {"n": "Hamdard Rooh Afza Sharbat", "u": "750 ml", "p": 160, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-15"},
  {"n": "Kissan Fresh Mango Syrup", "u": "700 g", "p": 130, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-16"},
  {"n": "Britannia Roll Yo! Swiss Roll - Strawberry", "u": "28 g", "p": 10, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-17"},
  {"n": "Britannia Gobbles Fruity Fun Cake", "u": "90 g", "p": 22, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-18"},
  {"n": "Pass Pass Pulse Candy", "u": "72 g (pack)", "p": 20, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-19"},
  {"n": "Rajnigandha Pan Masala Pouch", "u": "3.3 g x 12", "p": 60, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-20"},
  {"n": "Epigamia Greek Yogurt - Mango", "u": "90 g", "p": 45, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-21"},
  {"n": "Nestle A+ Greek Yogurt - Blueberry", "u": "90 g", "p": 40, "m": 0, "c": "Sweet Tooth", "h": "sweet-tooth.html", "i": "images/sweet-tooth/sweet-tooth-22"},
  {"n": "Maggi 2 Minutes Instant Noodles", "u": "420 g", "p": 79, "m": 90, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-01"},
  {"n": "Yippee Magic Masala Instant Noodles with Added Veggies", "u": "435.6 g", "p": 81, "m": 90, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-02"},
  {"n": "McCain French Fries (Frozen)", "u": "420 g", "p": 117, "m": 129, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-03"},
  {"n": "Godrej Yummiez Cheesy Pizza Fingers", "u": "250 g", "p": 84, "m": 150, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-04"},
  {"n": "ITC Master Chef Chicken Seekh Kebab", "u": "500 g", "p": 286, "m": 350, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-05"},
  {"n": "Godrej Yummiez Chicken Nuggets", "u": "450 g", "p": 230, "m": 320, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-06"},
  {"n": "Del Monte Durum Wheat Pasta - Penne Rigate", "u": "500 g", "p": 149, "m": 280, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-07"},
  {"n": "Bambino Pasta - Penne", "u": "250 g", "p": 50, "m": 0, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-08"},
  {"n": "Gits Khaman Dhokla Snack Mix", "u": "500 g", "p": 121, "m": 132, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-09"},
  {"n": "MTR Masala Rava Idli Mix", "u": "500 g", "p": 125, "m": 133, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-10"},
  {"n": "Yoga Bar Chocolate Chunk Nut Multigrain Energy Bar", "u": "35 g", "p": 33, "m": 45, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-11"},
  {"n": "The Whole Truth Double Cocoa Protein Bar", "u": "52 g", "p": 90, "m": 0, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-12"},
  {"n": "Knorr Thick Tomato Soup", "u": "51 g", "p": 61, "m": 64, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-13"},
  {"n": "Knorr Classic Sweet Corn Vegetable Soup", "u": "42 g", "p": 61, "m": 64, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-14"},
  {"n": "Safal Frozen Green Peas", "u": "500 g", "p": 135, "m": 0, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-15"},
  {"n": "Safal Frozen Mixed Vegetables", "u": "500 g", "p": 99, "m": 0, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-16"},
  {"n": "Haldiram's Minute Khana Dal Makhani Ready to Eat", "u": "300 g", "p": 89, "m": 0, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-17"},
  {"n": "Heinz Baked Beans in Tomato Sauce", "u": "415 g", "p": 172, "m": 199, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-18"},
  {"n": "Weikfield Mango Jelly Mix", "u": "90 g", "p": 58, "m": 60, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-19"},
  {"n": "Betty Crocker Classic Pancake Mix (Original)", "u": "250 g", "p": 166, "m": 195, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-20"},
  {"n": "Keya Pizza Oregano", "u": "80 g", "p": 99, "m": 119, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-21"},
  {"n": "Keya Red Chilli Flakes", "u": "40 g", "p": 86, "m": 99, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-22"},
  {"n": "iD Idli & Dosa Batter", "u": "1 kg", "p": 130, "m": 0, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-23"},
  {"n": "Amma's Special Dosa/Idli Batter", "u": "1 kg", "p": 99, "m": 0, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-24"},
  {"n": "Vezlay Ready to Cook Plant Based Meat", "u": "200 g", "p": 238, "m": 250, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-25"},
  {"n": "PFC Foods Plant-Based Classic Chicken Nuggets", "u": "400 g", "p": 308, "m": 350, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-26"},
  {"n": "Samyang Ramen Instant Noodles - Hot Chicken Flavour", "u": "140 g", "p": 131, "m": 140, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-27"},
  {"n": "Del Monte Foodcraft Durum Wheat Pasta - Spaghetti", "u": "400 g", "p": 69, "m": 89, "c": "Breakfast & Instant Food", "h": "breakfast-instant-food.html", "i": "images/breakfast-instant-food/breakfast-instant-food-28"},
  {"n": "Bingo Mad Angles Achaari Masti Crisps", "u": "60 g", "p": 19, "m": 20, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-01"},
  {"n": "Lay's India's Magic Masala Potato Chips", "u": "58 g", "p": 21, "m": 25, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-02"},
  {"n": "Britannia Toastea Premium Bake Rusk", "u": "250 g", "p": 42, "m": 50, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-03"},
  {"n": "Parle Real Elaichi Premium Rusk", "u": "291.2 g", "p": 54, "m": 60, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-04"},
  {"n": "Yoga Bar Chocolate Chunk Nut Multigrain Energy Bar", "u": "35 g", "p": 33, "m": 45, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-05"},
  {"n": "RiteBite Max Protein Daily Choco Almond Bar", "u": "50 g", "p": 70, "m": 71, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-06"},
  {"n": "Doritos Cheese Nachos", "u": "71 g", "p": 35, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-07"},
  {"n": "Cornitos Sizzlin Jalapeno Nachos Chips", "u": "65 g", "p": 57, "m": 60, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-08"},
  {"n": "Haldiram's Bhujia", "u": "200 g", "p": 60, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-09"},
  {"n": "Haldiram's Aloo Bhujia", "u": "210 g", "p": 55, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-10"},
  {"n": "ACT II Classic Caramel Popcorn", "u": "70 g", "p": 70, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-11"},
  {"n": "4700BC Himalayan Salt Caramel Popcorn", "u": "125 g", "p": 44, "m": 88, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-12"},
  {"n": "Haldiram's Classic Salted Peanuts", "u": "200 g", "p": 60, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-13"},
  {"n": "Haldiram's Moong Dal Namkeen", "u": "200 g", "p": 60, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-14"},
  {"n": "Nutraj Himalayan Pink Salt Flavoured Makhana", "u": "70 g", "p": 155, "m": 278, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-15"},
  {"n": "Mr. Makhana Pudina Party Flavoured Makhana", "u": "21 g", "p": 47, "m": 50, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-16"},
  {"n": "Lijjat Plain Urad Dal Papad", "u": "200 g", "p": 80, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-17"},
  {"n": "Ramji Mix Fryums", "u": "200 g", "p": 58, "m": 80, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-18"},
  {"n": "Kettle Studio Potato Chips - Himalayan Pink Salt", "u": "113 g", "p": 99, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-19"},
  {"n": "Cheetos Crunchy Cheese Flavoured Crisps", "u": "99.2 g", "p": 449, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-20"},
  {"n": "True Elements Dark Chocolate Granola", "u": "700 g", "p": 475, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-21"},
  {"n": "Yoga Bar Muesli - Almond & Quinoa Crunch", "u": "400 g", "p": 390, "m": 0, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-22"},
  {"n": "4700BC Nutty Tuxedo Chocolate Gourmet Popcorn Tin", "u": "375 g", "p": 523, "m": 550, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-23"},
  {"n": "Open Secret Healthy Cookie Namkeen Snacks Combo", "u": "334 g", "p": 481, "m": 534, "c": "Snacks & Munchies", "h": "snacks-munchies.html", "i": "images/snacks-munchies/snacks-munchies-24"},
  {"n": "Coca-Cola Gift Pack", "u": "6 x 250 ml", "p": 180, "m": 210, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-01"},
  {"n": "Tropicana Juice Gift Pack", "u": "4 x 200 ml", "p": 160, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-02"},
  {"n": "Coca-Cola", "u": "750 ml", "p": 40, "m": 45, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-03"},
  {"n": "Pepsi", "u": "2.25 L", "p": 95, "m": 105, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-04"},
  {"n": "Real Fruit Power Mixed Fruit", "u": "1 L", "p": 110, "m": 120, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-05"},
  {"n": "Tropicana Guava Delight", "u": "1 L", "p": 115, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-06"},
  {"n": "Maaza Mango Drink", "u": "1.2 L", "p": 75, "m": 80, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-07"},
  {"n": "Slice Mango Drink", "u": "1.2 L", "p": 78, "m": 85, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-08"},
  {"n": "Tropicana 100% Orange Juice", "u": "1 L", "p": 130, "m": 145, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-09"},
  {"n": "Real 100% Pomegranate Juice", "u": "1 L", "p": 150, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-10"},
  {"n": "Hamdard Rooh Afza Syrup", "u": "750 ml", "p": 210, "m": 235, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-11"},
  {"n": "Kissan Orange Squash", "u": "700 ml", "p": 140, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-12"},
  {"n": "Patanjali Amla Juice", "u": "1 L", "p": 110, "m": 125, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-13"},
  {"n": "Kapiva Aloe Vera Juice", "u": "1 L", "p": 299, "m": 349, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-14"},
  {"n": "Red Bull Energy Drink", "u": "250 ml", "p": 125, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-15"},
  {"n": "Monster Energy", "u": "350 ml", "p": 110, "m": 125, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-16"},
  {"n": "Real Activ Coconut Water", "u": "200 ml", "p": 40, "m": 45, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-17"},
  {"n": "Raw Pressery Tender Coconut Water", "u": "200 ml", "p": 55, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-18"},
  {"n": "Amul Lassi", "u": "200 ml", "p": 25, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-19"},
  {"n": "Amul Kool Chocolate Milkshake", "u": "200 ml", "p": 30, "m": 35, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-20"},
  {"n": "Bisleri Mineral Water", "u": "1 L", "p": 20, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-21"},
  {"n": "Ice Cubes", "u": "500 g", "p": 30, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-22"},
  {"n": "Nescafe Ready-to-Drink Cold Coffee", "u": "180 ml", "p": 60, "m": 70, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-23"},
  {"n": "Lipton Peach Ice Tea", "u": "250 ml", "p": 40, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-24"},
  {"n": "Bisleri Club Soda", "u": "750 ml", "p": 25, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-25"},
  {"n": "Schweppes Tonic Water", "u": "300 ml", "p": 65, "m": 75, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-26"},
  {"n": "San Pellegrino Sparkling Water", "u": "750 ml", "p": 195, "m": 0, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-27"},
  {"n": "Ramune Japanese Soda", "u": "200 ml", "p": 220, "m": 250, "c": "Cold Drinks & Juices", "h": "cold-drinks-juices.html", "i": "images/cold-drinks-juices/cold-drinks-juices-28"}
];