#!/usr/bin/env node
// Regenerates js/search-data.js from the product lists in the category pages.
//
//   node tools/build-search.js          rebuild once
//   node tools/build-search.js --watch  rebuild automatically whenever a page or data file changes
//   node tools/build-search.js --check  exit 1 if search-data.js is out of date (for CI / git hooks)
//
// Sources (nothing to configure - new pages are picked up automatically):
//   *.html with a `window.SECTION = {...}` block   (except section-template.html)
//   js/paan-corner-data.js                          (window.PAAN_CORNER)
// Category names come from js/categories.js (falls back to SECTION.title).
// No dependencies; needs Node 14+.

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "js", "search-data.js");
const SKIP = new Set(["section-template.html"]);

const pad = (n) => (n < 10 ? "0" : "") + n;

function run(code, file) {
  const sandbox = { window: {} };
  try {
    vm.runInNewContext(code, sandbox, { filename: file, timeout: 2000 });
  } catch (e) {
    throw new Error(file + ": " + e.message);
  }
  return sandbox.window;
}

function categoryNames() {
  // categories.js uses window.CATEGORIES = [[slug, name], ...].map(...) and window.OFFERS (ignored).
  const w = run(fs.readFileSync(path.join(ROOT, "js", "categories.js"), "utf8"), "js/categories.js");
  const map = {};
  (w.CATEGORIES || []).forEach((c) => (map[c.slug] = c.name));
  return map;
}

function row(name, unit, price, mrp, cat, slug, file) {
  return { n: name, u: unit, p: price, m: mrp || 0, c: cat, h: slug + ".html", i: "images/" + slug + "/" + file };
}

function build() {
  const names = categoryNames();
  const rows = [];
  const warnings = [];

  // Generic section pages (image = images/<slug>/<slug>-<nn>, nn = position in the list).
  fs.readdirSync(ROOT).filter((f) => f.endsWith(".html") && !SKIP.has(f)).sort().forEach((f) => {
    const html = fs.readFileSync(path.join(ROOT, f), "utf8");
    const blocks = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((m) => m[1]).filter((s) => s.includes("window.SECTION"));
    if (!blocks.length) return;
    const S = run(blocks[0], f).SECTION;
    if (!S || !Array.isArray(S.products)) { warnings.push(f + ": SECTION has no products array"); return; }
    const slug = S.slug || path.basename(f, ".html");
    if (slug + ".html" !== f) warnings.push(f + ": SECTION.slug is \"" + slug + "\" but the file is " + f + " - search links would break");
    const cat = names[slug] || S.title || slug;
    S.products.forEach((p, i) => rows.push(row(p[0], p[1], p[2], p[3], cat, slug, slug + "-" + pad(i + 1))));
  });

  // Paan Corner: sub-categories are merged into one grid, numbered continuously.
  const pcFile = path.join(ROOT, "js", "paan-corner-data.js");
  if (fs.existsSync(pcFile)) {
    const subs = run(fs.readFileSync(pcFile, "utf8"), "js/paan-corner-data.js").PAAN_CORNER || [];
    const cat = names["paan-corner"] || "Paan Corner";
    let n = 0;
    subs.forEach((s) => s.products.forEach((p) => rows.push(row(p[0], p[1], p[2], p[3], cat, "paan-corner", "paan-corner-" + pad(++n)))));
  }

  rows.forEach((r) => {
    if (typeof r.n !== "string" || typeof r.u !== "string" || typeof r.p !== "number")
      warnings.push("Bad product row (need [name, unit, price, mrp?]): " + JSON.stringify(r));
  });

  const header =
    "// Search index used by the header search box (js/header.js).\n" +
    "// AUTO-GENERATED by tools/build-search.js - do not edit by hand; your changes will be overwritten.\n" +
    "// To add or change a product, edit its category page (or js/paan-corner-data.js) and run: node tools/build-search.js  (or npm run watch)\n" +
    "// One row per product: n = name, u = unit, p = price, m = MRP (0 if none), c = category title, h = category page, i = image path without extension.\n";
  const body = "window.SEARCH_INDEX = [\n" + rows.map((r) => "  " + JSON.stringify(r)).join(",\n") + "\n];\n";
  return { text: header + body, count: rows.length, warnings };
}

function write() {
  const { text, count, warnings } = build();
  warnings.forEach((w) => console.warn("warning: " + w));
  const old = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (old === text) { console.log("search-data.js already up to date (" + count + " products)"); return false; }
  fs.writeFileSync(OUT, text);
  console.log("search-data.js updated (" + count + " products)");
  return true;
}

const arg = process.argv[2];
if (arg === "--check") {
  const { text } = build();
  const old = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (old !== text) { console.error("js/search-data.js is out of date. Run: node tools/build-search.js"); process.exit(1); }
  console.log("search-data.js is up to date");
} else if (arg === "--watch") {
  const safe = () => { try { write(); } catch (e) { console.error("build failed: " + e.message); } };
  safe();
  let timer;
  const kick = (_ev, f) => {
    clearTimeout(timer); timer = setTimeout(safe, 150);
  };
  fs.watch(ROOT, (ev, f) => { if (f && f.endsWith(".html")) kick(ev, f); });
  fs.watch(path.join(ROOT, "js"), (ev, f) => { if (f === "paan-corner-data.js" || f === "categories.js") kick(ev, f); });
  console.log("Watching pages and data files... (Ctrl+C to stop)");
} else {
  try { write(); } catch (e) { console.error("build failed: " + e.message); process.exit(1); }
}
